insert into authorEntities (id, first_name, last_name) values (1, 'Alfie', 'Larrie');
insert into authorEntities (id, first_name, last_name) values (2, 'Galina', 'Colebourn');
insert into authorEntities (id, first_name, last_name) values (3, 'Udall', 'de Nore');
insert into authorEntities (id, first_name, last_name) values (4, 'Aube', 'Flude');
insert into authorEntities (id, first_name, last_name) values (5, 'Inger', 'Wogden');
insert into authorEntities (id, first_name, last_name) values (6, 'Vlad', 'McComb');
insert into authorEntities (id, first_name, last_name) values (7, 'Kirstin', 'Scathard');
insert into authorEntities (id, first_name, last_name) values (8, 'Cristionna', 'Syder');
insert into authorEntities (id, first_name, last_name) values (9, 'Jeannine', 'Gredden');
insert into authorEntities (id, first_name, last_name) values (10, 'Chic', 'Mc Faul');
insert into authorEntities (id, first_name, last_name) values (11, 'Caddric', 'Iwanowski');
insert into authorEntities (id, first_name, last_name) values (12, 'Konstance', 'Goldstein');
insert into authorEntities (id, first_name, last_name) values (13, 'Dorita', 'Beggs');
insert into authorEntities (id, first_name, last_name) values (14, 'Barri', 'Avrahamian');
insert into authorEntities (id, first_name, last_name) values (15, 'Anetta', 'Tunnadine');
insert into authorEntities (id, first_name, last_name) values (16, 'Merrie', 'Towle');
insert into authorEntities (id, first_name, last_name) values (17, 'Fremont', 'Featherston');
insert into authorEntities (id, first_name, last_name) values (18, 'Roley', 'Mates');
insert into authorEntities (id, first_name, last_name) values (19, 'Stormy', 'Nurse');
insert into authorEntities (id, first_name, last_name) values (20, 'Gaynor', 'Tissell');
insert into authorEntities (id, first_name, last_name) values (21, 'Martita', 'Long');
insert into books (id, price, price_old, title, author_id) values (1, 1143, 3030.8547, 'Lotstring', 19);
insert into books (id, price, price_old, title, author_id) values (2, 2686, 1384.4283, 'Prodder', 13);
insert into books (id, price, price_old, title, author_id) values (3, 2896, 2199.9052, 'Bigtax', 20);
insert into books (id, price, price_old, title, author_id) values (4, 932, 3430.5484, 'It', 16);
insert into books (id, price, price_old, title, author_id) values (5, 2470, 3948.5566, 'Veribet', 7);
insert into books (id, price, price_old, title, author_id) values (6, 2635, 3892.7078, 'Stim', 4);
insert into books (id, price, price_old, title, author_id) values (7, 1823, 2387.6033, 'Redhold', 6);
insert into books (id, price, price_old, title, author_id) values (8, 575, 3195.1671, 'Flowdesk', 12);
insert into books (id, price, price_old, title, author_id) values (9, 1078, 2266.2732, 'Lotstring', 12);
insert into books (id, price, price_old, title, author_id) values (10, 984, 1375.2391, 'Treeflex', 12);
insert into books (id, price, price_old, title, author_id) values (11, 1944, 1598.0966, 'Subin', 1);
insert into books (id, price, price_old, title, author_id) values (12, 546, 3728.0794, 'Otcom', 18);
insert into books (id, price, price_old, title, author_id) values (13, 982, 1702.4589, 'Fintone', 21);
insert into books (id, price, price_old, title, author_id) values (14, 1050, 2318.5816, 'Job', 10);
insert into books (id, price, price_old, title, author_id) values (15, 2044, 3366.1165, 'Wrapsafe', 4);
insert into books (id, price, price_old, title, author_id) values (16, 553, 3619.6346, 'Vagram', 14);
insert into books (id, price, price_old, title, author_id) values (17, 1177, 3300.0265, 'Redhold', 20);
insert into books (id, price, price_old, title, author_id) values (18, 2853, 2537.8417, 'Duobam', 13);
insert into books (id, price, price_old, title, author_id) values (19, 2106, 3418.9643, 'Zamit', 11);
insert into books (id, price, price_old, title, author_id) values (20, 2221, 1065.4032, 'Viva', 13);
insert into books (id, price, price_old, title, author_id) values (21, 1890, 2552.6558, 'Opela', 7);
