spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?useSSL=false
    username: root
    password: QwEr3466
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false

someParameter:
  value: 5463