package com.example.MyBookShopApp.data.author;

import com.example.MyBookShopApp.data.book.links.Book2AuthorEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.util.List;

@Entity
@Getter
@Setter
@RequiredArgsConstructor
@Table(name = "authors")
@ApiModel("Data model of author entity")
public class AuthorEntity {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@ApiModelProperty("author id generated by DB")
	private Integer id;

	@Column(columnDefinition = "VARCHAR(255)")
	private String photo;

	@Column(columnDefinition = "VARCHAR(255) NOT NULL")
	private String slug;

	@Column(columnDefinition = "VARCHAR(255) NOT NULL")
	private String name;

	@Column(columnDefinition = "TEXT")
	private String description;

	@OneToMany(mappedBy = "author")
	@JsonIgnore
	@ToString.Exclude
	private List<Book2AuthorEntity> books2Authors;

}
